name: Build a Blog Website 

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}      

      - name: initialize
        run: terraform init
         
      - name: apply
        run: terraform apply -auto-approve

          

